name: main
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
        with:
          tags: docker-eicar
